server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/rooms/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
